[workspace]
members = [
    "raw",
    "api",
    "apps",
]
#"config",  Must NOT be among the workspace; it does not need/want the common '.cargo/config.toml'

resolver = "3"
    # virtual workspace TOML (that's us) needs this explicitly for parsing guidance (same as release 2024 in the members)

[workspace.dependencies]
#esp-idf-sys = { version = "0.37", default-features = false }
esp-idf-svc = { version = "0.52", default-features = false, features = ["native"] }
log = { version = "0.4" }

embassy-time = { version = "0.5", features = ["log"] }

embuild = { version = "0.33.1", features = ["espidf"] }

# Referenced in '{api|apps}/Cargo.toml':
#   <<
#       [lints]
#       workspace = true
#   <<
[workspace.lints.rust]
#unexpected_cfgs = { level = "warn", check-cfg = ['cfg(esp_idf_version_at_least_5_5_3)'] }

# We don't use
#[profile.dev]
#panic = "unwind"

[profile.release]
opt-level = "s"
