[workspace]
members = [
  "main",
  "raw",
]
resolver = "3" # release 2024 in the members

# Instead of '.crate/config.toml', 'esp-idf-sys' configs could be provided here
#|[workspace.metadata.esp-idf-sys]
#|esp_idf_tools_install_dir = "global"
#|mcu = "esp32c6"
#|esp_idf_sdkconfig_defaults = ["sdkconfig.defaults"]
#|esp_idf_version = "5.5.3"

[workspace.lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(esp_idf_version_at_least_5_5_3)'] }

[profile.release]
opt-level = "s"
