# needed for building 'riscv32imac-esp-espidf' core
[toolchain]

# Building 'raw' on 'nightly' is broken (Apple silicon), 20-Aug-26 (12-Aug-26):
#   <<
#     error[E0425]: cannot find value `AT_FDCWD` in crate `libc`
#     --> /home/lima/.rustup/toolchains/nightly-aarch64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/fs/unix.rs:1896:38
#     |
#     1896 |                 libc::fchmodat(libc::AT_FDCWD, p.as_ptr(), perm.mode, 0)
#     |                                      ^^^^^^^^ not found in `libc`
#   <<
channel = "nightly-2026-07-14"  # 1.99.0 nightly
#channel = "nightly-2026-08-01" # fails
#channel = "nightly"

components = ["rust-src", "clippy", "rustfmt"]
    # rustfmt: needed for 'make manual' to provide nice-looking 'tmp/bindings_0.rs'

# Automatically installs the target, if you don't have it, yet.
# However. ESP32 don't come with pre-built std libraries. In fact, this causes a warning in the build output.
# Let's omit it.
#targets = [ "riscv32imac-esp-espidf" ]
