#
# Setup for the Zigbee node.
#
[network]
primary_channels = [13]
secondary_channels = "all"

[platform]
#storage_partition_name = "zb_storage"
storage_partition_name = "nvs"  # since esp-zigbee-lib 2.0.4

[node]
type = "coordinator"
install_code_policy = false
max_children = 10

[endpoint.defaults]
manufacturer_name = "Your name"
model_identifier = "Your model"

[endpoint.10]
device_type = "color_dimmable_light"
