
use core::{
    fmt,
    time::Duration
};

use strum;

use ezb_node_raw::{
    //ezb_app_signal_type_t,
    ezb_zdo_signal_device_annce_params_t,
    //zb_app_signal_get_params,
    ezb_zdo_signal_leave_params_t,
    //ezb_nwk_signal_device_associated_params_t,
    ezb_zdo_signal_leave_indication_params_t,
    //R ezb_zdo_signal_can_sleep_params_t,
    ezb_zdo_signal_device_authorized_params_t,
    ezb_zdo_signal_device_update_params_t,
    //R ezb_zdo_signal_nwk_status_indication_params_t,
    ezb_zdo_signal_device_unavailable_params_t,
    ezb_bdb_signal_simple_params_t,
    ezb_nwk_signal_network_status_params_t,
    ezb_nwk_network_status_t,
    ezb_nwk_signal_permit_join_status_params_t,
    ezb_app_signal_type_e,
    //ezb_app_signal_t,
    ezb_bdb_comm_status_e,
};

#[cfg(false)]   // feature = "touchlink"
use crate::raw::{
    esp_zb_bdb_signal_touchlink_nwk_started_params_t,
    esp_zb_bdb_signal_touchlink_nwk_joined_router_t,
    esp_zb_bdb_signal_touchlink_nwk_started_params_t,
};

use crate::utils::IeeeAddr;

// Note:
//      "The following signals though provided, will never be generated by the Zigbee stack in v2.x:" |1|
//          |1|: migration guide 1.x -> 2.0 > Behavioural changes
//              -> https://docs.espressif.com/projects/esp-zigbee-sdk/en/latest/esp32/migration-guide/v2.x/compat.html#behavioral-changes
//
//      Such signals are - for now - kept in the code, but conditioned out.

/**
* Enumeration of Zigbee APP signals
*
* @note Only signals actually used in 'esp-zigbee-sdk' 2.0 are presented.
*/
#[derive(Debug, Clone)]
pub enum AppSignal {

    #[cfg(false)]   // not generated by v2.x
    /**
    * Overview:
    * - The device has started in non-BDB commissioning mode.
    *
    * When generated:
    * - After the device has started and completed non-BDB commissioning.
    * - In case of a commissioning error.
    */
    // Status code:
    //  - ESP_OK: Device has started and joined the network.
    //  - ESP_FAIL: Device startup failure.
    //
    // Payload:
    //  - None
    //
    ZdoSignalDefaultStart{ joined: bool },

    /**
    * Overview:
    * - Stack framework (scheduler, buffer pool, NVRAM, etc.) startup complete,
    *   ready for initializing bdb commissioning.
    *
    * When generated:
    * - When the stack starts using the ezb_start(false) method.
    */
    // Payload:
    //  - None
    //
    ZdoSignalSkipStartup,

    #[cfg(false)]   // not generated by v2.x
    /**
    * Overview:
    * - Indicates corrupted or incorrect signal information.
    *
    * When generated:
    * - When incorrect signal information is detected.
    */
    // Status code:
    //  - None
    //
    // Payload:
    //  - None
    ZdoSignalError,

    /**
    * Overview:
    * - Indicates that the device itself has left the network.
    *
    * When generated:
    * - Upon receiving the Leave command.
    */
    // Payload:
    //  - Refer to 'ezb_zdo_signal_leave_params_t'
    //
    ZdoSignalLeave{
        leave_type_X: u8,   // really enum of 'esp_zb_nwk_leave_type_t'
    },

    /**
    * Overview:
    * - Indicates that a device (child or neighbor) has left the network.
    *
    * When generated:
    * - When the leave command is received from the device.
    */
    // Payload:
    // - Refer to ezb_zdo_signal_leave_indication_params_t
    ZdoSignalLeaveIndication{
        short_addr: u16,
        device_addr: IeeeAddr,
        leave_type_X: u8
    },

    /**
    * Overview:
    * - Indicates that a Zigbee device has joined or rejoined the network.
    *
    * When generated:
    * - Upon receiving the device_annce command.
    */
    // Status code:
    //  - ESP_OK: device_annce command was received.
    //
    // Payload:
    //  - Refer to 'ezb_zdo_signal_device_annce_params_t'
    //
    ZdoSignalDeviceAnnce{
        short_addr: u16,
        device_addr: IeeeAddr,
        capability_X: u8    // tbd. consider if we want to make an enum
    },

    /**
    * Overview:
    * - Notify that the destination device is unavailable.
    *
    * When generated:
    *  - When the stack could not send a packet over NWK or APS, for example:
    *      - No ACK on the MAC layer;
    *      - No response to a network address request;
    *      - No APS-ACK to an APS packet.
    */
    // Payload:
    //  - Refer to ezb_zdo_signal_device_unavailable_params_t
    ZdoSignalDeviceUnavailable{
        device_addr: IeeeAddr,
        short_addr: u16
    },

    /**
    * Overview:
    * - Indicates that a device has joined, rejoined, or left the network from the Trust Center or its parents.
    *
    * When generated:
    *  - Standard device secured rejoin.
    *  - Standard device unsecured join.
    *  - Device left.
    *  - Standard device trust center rejoin.
    */
    // Payload:
    // - Refer to ezb_zdo_signal_device_update_params_t
    ZdoSignalDeviceUpdate{
        device_addr: IeeeAddr,
        short_addr: u16,
        status_X: u8,    // tbd. enum? ezb_zdo_upddev_status_t
        tc_action_X: u8,    // tbd. enum? ezb_zdo_tc_action_t
        parent_short: u16
    },

    /**
    * Overview:
    * - Indicates that a new device has been authorized by the Trust Center in the network.
    *
    * When generated:
    *  - Upon successful authorization.
    *  - Upon authorization failure.
    *  - Upon authorization timeout.
    */
    // Payload:
    //  - Refer to ezb_zdo_signal_device_authorized_params_t
    ZdoSignalDeviceAuthorized{
        device_addr: IeeeAddr,
        short_addr: u16,
        type_X: u8,    // tbd. enum? ezb_zdo_auth_type_t
        status_X: u8,  // tbd. enum? ezb_zdo_auth_status_t
    },

    /**
    * Overview:
    * - Indicate the basic network information of factory new device has been initialized,
    *   ready for Zigbee commissioning
    *
    * When generated:
    * - Upon the basic device behavior has been initialization
    */
    // Payload:
    //  - Refer to ezb_bdb_status_simple_params_t (which has '.status: u8').
    //      Note: The 'u8' is commented to "refer to 'ezb_bdb_status_t' but such a type does not exist. It may mean
    //          'ezb_bdb_comm_status_e'.
    //
    BdbSignalDeviceFirstStart(BdbStatus),

    /**
    * Overview:
    * - Indicate device joins or rejoins network from the configured network information.
    *
    * When generated:
    * - Upon the device joining or rejoining Zigbee network using configuration network information.
    */
    // Payload:
    //  - Refer to ezb_bdb_signal_simple_params_t
    BdbSignalDeviceReboot(BdbStatus),

    /**
    * Overview:
    * - Indicates the completion of BDB network steering.
    *
    * When generated:
    * - When the device initiates the network steering commissioning process.
    *                       ^^--- tbd. "initiates"?
    */
    // Payload:
    //  - Refer to ezb_bdb_signal_simple_params_t
    BdbSignalSteering(BdbStatus),

    /**
    * Overview:
    * - Indicates the completion of BDB network formation.
    *
    * When generated:
    * - When the device initiates the network formation commissioning process.
    *                       ^^--- tbd. "initiates"?
    */
    // Payload:
    //  - Refer to ezb_bdb_signal_simple_params_t
    BdbSignalFormation(BdbStatus),

    /**
    * Overview:
    * - Indicates the completion of BDB finding and binding (F&B) for a initiator endpoint.
    *
    * When generated:
    * - When F&B initiator timeout
    */
    // Payload:
    //  - Refer to ezb_bdb_signal_simple_params_t
    BdbSignalFindingAndBindingInitiatorFinished(BdbStatus),

    /**
    * Overview:
    * - Indicates the completion of BDB finding and binding (F&B) for a target endpoint.
    *
    * When generated:
    * - When F&B target timeout.
    */
    // Payload:
    //  - Refer to ezb_bdb_signal_simple_params_t
    BdbSignalFindingAndBindingTargetFinished(BdbStatus),

    /**
    * Overview:
    * - Indicates the completion of Touchlink commissioning for a initiator.
    *
    * When generated:
    *  - EZB_BDB_STATUS_SUCCESS: If the touchlink initiator successfully completes the commissioning procedure.
    *  - EZB_BDB_STATUS_NO_SCAN_RESPONSE: If no scan response is received while scanning for targets.
    *  - EZB_BDB_STATUS_NOT_PERMITTED: If the network type is centralized, or the initiator is in an incorrect commissioning state.
    *  - EZB_BDB_STATUS_NO_NETWORK: If the Touchlink initiator fails during the network_start process.
    *  - EzbBdbStatusNotAaCapable: If the initiator is not address assignment capable during touchlink.
    *  - EZB_BDB_STATUS_TARGET_FAILURE: If the touchlink initiator fails during the join_router or join_ed process.
    */
    // Payload:
    //  - Refer to ezb_bdb_signal_simple_params_t
    #[cfg(false)]   // feature = "touchlink"
    BdbSignalTouchlinkInitiatorFinished,

    /**
    * Overview:
    * - Indicates the completion of Touchlink commissioning for a target.
    *
    * When generated:
    *  - EZB_BDB_STATUS_SUCCESS: If the touchlink target successfully completes the commissioning procedure.
    *  - EZB_BDB_STATUS_TARGET_FAILURE: If the touchlink target times out during commissioning (no target selected)
    *       or during a transaction (target selected but no subsequent step).
    *  - EZB_BDB_STATUS_NO_NETWORK: If the touchlink target is selected but fails during the network_start, join_router,
    *       or join_ed process.
    */
    // Payload:
    //  - Refer to ezb_bdb_signal_simple_params_t
    #[cfg(false)]   // feature = "touchlink"
    BdbSignalTouchlinkTargetFinished,

    /**
    * Overview:
    * - [Obsolete] Indicates that a new device has initiated an association procedure.
    *
    * When generated:
    * - When a new device is associated.
    */
    // Status code:
    //  - ESP_OK: The new device was successfully associated.
    //
    // Payload:
    //  - Refer to ezb_nwk_signal_device_associated_params_t
    #[deprecated(note="Marked 'obsolete' by esp-zigbee-lib docs")]
    #[cfg(false)]   // no 'ezb_nwk_signal_device_associated_params_t'; would not build or we need to guess param types
    NwkSignalDeviceAssociated{
        device_addr: IeeeAddr
    },

    #[cfg(false)]   //R not generated by v2.x
    /**
    * Overview:
    * - Indicates the device can enter sleep mode.
    *
    * When generated:
    * - When the stack determines that the device is eligible to enter sleep mode.
    */
    // Status code:
    //  - ESP_OK: The device can enter sleep mode.
    //
    // Payload:
    //  - Refer to esp_zb_zdo_signal_can_sleep_params_t
    CommonSignalCanSleep{
        sleep_duration: Duration,
    },

    #[cfg(false)]   //R not generated by v2.x
    /**
    * Overview:
    * - Indicates whether a specific part of the production configuration was found.
    *
    * When generated:
    * - After restoring the production configuration.
    */
    // Status code:
    //  - ESP_OK: Production configuration successfully loaded from storage.
    //  - ESP_FAIL: No production configuration found in storage.
    //
    // Payload:
    // - None
    ZdoSignalProductionConfigReady{ success: bool },

    /**
    * Overview:
    * - Indicates that the Neighbor Table has expired, and no active route links remain.
    *
    * When generated:
    * - When all routers in the neighbor table were stale.
    */
    // Payload:
    // - None
    NwkSignalNoActiveLinksLeft,

    /**
    * Overview:
    * - Detects a PAN ID conflict and inquires for a resolution.
    *
    * When generated:
    *  - Upon detecting a PAN ID conflict.
    */
    // Payload:
    //  - None
    NwkSignalPanidConflictDetected,

    /**
    * Overview:
    * - Indicates that a network failure has been detected.
    *
    * When generated:
    * - Triggered when the network encounters a failure and the application can implement
    *   error handling based on the reported status.
    */
    // Payload:
    //  - Refer to ezb_nwk_signal_network_status_params_t
    NwkSignalNetworkStatus {
        status: ezb_nwk_network_status_t,
        network_addr: u16,
        unknown_command_id: u8
    },

    /**
    * Overview:
    * - Indicates the status of the network (open or closed).
    *
    * When generated:
    *  - When the network is opened.
    *  - When the network is closed.
    */
    // Payload:
    //  - Refer to ezb_nwk_signal_permit_join_status_params_t
    NwkSignalPermitJoinStatus{ is_opened_for: Option<Duration> },

    #[cfg(false)]   //R not generated by v2.x
    /**
    * Overview:
    * - Indicates that the Trust Center rejoin procedure has been completed.
    *
    * When generated:
    *  - Upon successful completion of the TC rejoin procedure by the device.
    */
    // Status code:
    //  - ESP_OK: TC rejoin completed successfully.
    //  - ESP_FAIL: Rejoin failed.
    //
    // Payload:
    //  - None
    BdbSignalTcRejoinDone{ success: bool },

    #[cfg(false)]   //R not generated by v2.x
    /**
    * Overview:
    * - Indicates the result of cancelling BDB steering.
    *
    * When generated:
    *  - When `esp_zb_bdb_cancel_steering()` is processed.
    */
    // Status code:
    //  - ESP_OK: Steering is cancelled successfully.
    //  - ESP_ERR_INVALID_STATE: Steering is not in progress.
    //  - ESP_FAIL: Failed to cancel steering.
    //
    // Payload:
    //  - None
    BdbSignalSteeringCancelled(Result<(),EspError>),

    #[cfg(false)]   //R not generated by v2.x
    /**
    * Overview:
    * - Notifies the result of cancelling BDB formation.
    *
    * When generated:
    *  - When `esp_zb_bdb_cancel_formation()` is processed.
    */
    // Status code:
    //  - ESP_OK: Formation is cancelled successfully.
    //  - ESP_ERR_INVALID_STATE: Formation is not in progress.
    //  - ESP_FAIL: Failed to cancel formation.
    //
    // Payload:
    //  - None
    BdbSignalFormationCancelled(Result<(),EspError>),

    /**
    * [ ] going to ask C upstreadm authors to provide a doc. Based on google.ai:
    *       "marker to show that some list or process has been successfully gone through."
    */
    End,
}

impl AppSignal {
    /**
    * Convert the application signal from C level to Rust so that type and params are contained within the
    * same enum.
    */
    pub(crate) fn from(p_type: ezb_app_signal_type_e, p_params: *const ::core::ffi::c_void) -> Option<Self> {
        use ezb_app_signal_type_e::*;    // signal values

        let happy_res = match p_type {
            EZB_ZDO_SIGNAL_SKIP_STARTUP => { // 1
                Self::ZdoSignalSkipStartup
            },
            EZB_ZDO_SIGNAL_LEAVE => { // 3
                let x = get_param::<ezb_zdo_signal_leave_params_t>(p_params);
                Self::ZdoSignalLeave {
                    leave_type_X: x.leave_type
                }
            },
            EZB_ZDO_SIGNAL_LEAVE_INDICATION => { // 4
                let x = get_param::<ezb_zdo_signal_leave_indication_params_t>(p_params);
                Self::ZdoSignalLeaveIndication {
                    short_addr: x.short_addr,
                    device_addr: x.device_addr.into(),
                    leave_type_X: x.leave_type
                        // EZB_ZDO_LEAVE_TYPE_RESET (0): "Leave without rejoin
                        // EZB_ZDO_LEAVE_TYPE_REJOIN (1): "Leave with rejoin"
                        // tbd. make them a Rust enum; keep the 'leave_type' key though this (currently) is just a boolean
                }
            },
            EZB_ZDO_SIGNAL_DEVICE_ANNCE => { // 5
                let x = get_param::<ezb_zdo_signal_device_annce_params_t>(p_params);
                Self::ZdoSignalDeviceAnnce {
                    short_addr: x.short_addr,
                    device_addr: x.device_addr.into(),
                    capability_X: x.capability
                }
            },
            EZB_ZDO_SIGNAL_DEVICE_UNAVAILABLE => { // 6
                let x = get_param::<ezb_zdo_signal_device_unavailable_params_t>(p_params);
                Self::ZdoSignalDeviceUnavailable {
                    device_addr: x.device_addr.into(),
                    short_addr: x.short_addr
                }
            },
            EZB_ZDO_SIGNAL_DEVICE_UPDATE => { // 7
                let x = get_param::<ezb_zdo_signal_device_update_params_t>(p_params);
                Self::ZdoSignalDeviceUpdate {
                    device_addr: x.device_addr.into(),
                    short_addr: x.short_addr,
                    status_X: x.status,
                    tc_action_X: x.tc_action,
                    parent_short: x.parent_short
                }
            },
            EZB_ZDO_SIGNAL_DEVICE_AUTHORIZED => { // 8
                let x = get_param::<ezb_zdo_signal_device_authorized_params_t>(p_params);
                Self::ZdoSignalDeviceAuthorized {
                    device_addr: x.device_addr.into(),
                    short_addr: x.short_addr,
                    type_X: x.type_,
                    status_X: x.status
                }
            },
            EZB_BDB_SIGNAL_DEVICE_FIRST_START => { // 256
                let x = get_param::<ezb_bdb_signal_simple_params_t>(p_params);
                Self::BdbSignalDeviceFirstStart(
                    BdbStatus::from_repr(x.status).unwrap()
                )
            },
            EZB_BDB_SIGNAL_DEVICE_REBOOT => { // 257
                let x = get_param::<ezb_bdb_signal_simple_params_t>(p_params);
                Self::BdbSignalDeviceReboot (
                    BdbStatus::from_repr(x.status).unwrap()
                )
            },
            EZB_BDB_SIGNAL_STEERING => { // 258
                let x = get_param::<ezb_bdb_signal_simple_params_t>(p_params);
                Self::BdbSignalSteering (
                    BdbStatus::from_repr(x.status).unwrap()
                )
            },
            EZB_BDB_SIGNAL_FORMATION => { // 259
                let x = get_param::<ezb_bdb_signal_simple_params_t>(p_params);
                Self::BdbSignalFormation (
                    BdbStatus::from_repr(x.status).unwrap()
                )
            },
            EZB_BDB_SIGNAL_FINDING_AND_BINDING_INITIATOR_FINISHED => { // 0x0d
                let x = get_param::<ezb_bdb_signal_simple_params_t>(p_params);
                Self::BdbSignalFindingAndBindingInitiatorFinished (
                    BdbStatus::from_repr(x.status).unwrap()
                )
            },
            EZB_BDB_SIGNAL_FINDING_AND_BINDING_TARGET_FINISHED => { // 260
                let x = get_param::<ezb_bdb_signal_simple_params_t>(p_params);
                Self::BdbSignalFindingAndBindingTargetFinished (
                    BdbStatus::from_repr(x.status).unwrap()
                )
            },
            #[cfg(false)]   // feature = "touchlink"
            EZB_BDB_SIGNAL_TOUCHLINK_INITIATOR_FINISHED => { // 262
                Self::BdbSignalTouchlinkInitiatorFinished
            },
            #[cfg(false)]   // feature = "touchlink"
            EZB_BDB_SIGNAL_TOUCHLINK_TARGET_FINISHED => { // 263
                Self::BdbSignalTouchlinkTargetFinished
            },
            #[cfg(false)]   // obsolete; param type not existing
            EZB_NWK_SIGNAL_DEVICE_ASSOCIATED => { // 512
                log::warn!("Caught {} marked 'obsolete' by C side docs", sig);

                let x = get_param::<ezb_nwk_signal_device_associated_params_t>(p_params);
                Self::NwkSignalDeviceAssociated {
                    device_addr: x.device_addr.into(),
                }
            },
            EZB_NWK_SIGNAL_NO_ACTIVE_LINKS_LEFT => { // 513
                Self::NwkSignalNoActiveLinksLeft
            },
            EZB_NWK_SIGNAL_PANID_CONFLICT_DETECTED => { // 514
                Self::NwkSignalPanidConflictDetected
            },
            EZB_NWK_SIGNAL_NETWORK_STATUS => { // 515
                let x = get_param::<ezb_nwk_signal_network_status_params_t>(p_params);

                // tbd. Instead of panicking, we _could_ just not match a signal which does not carry a valid enum.
                //      On the other hand, such a case would not arise from unexpected wire(less) traffic, but be a bug
                //      in 'esp-zigbee-lib'. Which means, probably we can panic? >:)
                //
                let status = ezb_nwk_network_status_t::parse(x.status)
                    .unwrap_or_else(|| {
                        panic!("EZB_NWK_SIGNAL_NETWORK_STATUS: unexpected '.status': {}", x.status);
                    });

                Self::NwkSignalNetworkStatus {
                    status,
                    network_addr: x.network_addr,
                    unknown_command_id: x.unknown_command_id
                }
            },
            EZB_NWK_SIGNAL_PERMIT_JOIN_STATUS => { // 516
                let ezb_nwk_signal_permit_join_status_params_t{ duration: x /*secs*/ } = get_param(p_params);
                    // YIEEEE!!!! ;)

                let iof = (x > 0).then(|| Duration::from_secs(x as _));
                Self::NwkSignalPermitJoinStatus{ is_opened_for: iof }
            },
            //
            EZB_APP_SIGNAL_END => { // 517
                Self::End
            },
            _ => {
                return None;
            }
        };
        Some(happy_res)
    }
}

/* Define 'Display' but use '{:?}' internally.
* - enough for debug needs, and takes care that caller does not need to use '{:?}'
*/
impl fmt::Display for AppSignal {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{:?}", self)
    }
}

/*
* The 'p_params' pointer points to signal specific structures with more information. Get them.
*/
fn get_param<T: Copy>(vp: *const ::core::ffi::c_void) -> T {
    assert!(!vp.is_null());
    let typed_ptr = vp as *const T;
    unsafe {
        typed_ptr.read_unaligned()  // do the right thing if the struct is "packed" ('esp-zigbee-lib' 2.0 API has 15 occurrences)
    }
}

use ezb_bdb_comm_status_e::*;

// Replication of 'ezb_bdb_comm_status_e' - so we don't need to leak 'raw' API.
//
#[repr(u8)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq, strum :: FromRepr, strum :: Display)]
pub enum BdbStatus {
    ///< The commissioning sub-procedure was successful.
    Success = 0,
    ///< One of the commissioning sub-procedures has started but is not yet
    /// complete.
    StatusInProgress = EZB_BDB_STATUS_IN_PROGRESS as _,
    ///< The initiator is not address assignment capable during touchlink.
    EzbBdbStatusNotAaCapable = EZB_BDB_STATUS_NOT_AA_CAPABLE as _,
    ///< A network has not been found during network steering or touchlink.
    EzbBdbStatusNoNetwork = EZB_BDB_STATUS_NO_NETWORK as _,
    ///< A node has not joined a network when requested during touchlink.
    TargetFailure = EZB_BDB_STATUS_TARGET_FAILURE as _,
    ///< A network could not be formed during network formation.
    FormationFailure = EZB_BDB_STATUS_FORMATION_FAILURE as _,
    ///< No response to an identify query command has been received during
    /// finding and binding.
    NoIdentifyQueryResponse = EZB_BDB_STATUS_NO_IDENTIFY_QUERY_RESPONSE as _,
    ///< A binding table entry could not be created due to insufficient space
    /// in the binding table during finding and binding.
    BindingTableFull = EZB_BDB_STATUS_BINDING_TABLE_FULL as _,
    ///< No response to a scan request inter-PAN command has been received
    /// during touchlink.
    NoScanResponse = EZB_BDB_STATUS_NO_SCAN_RESPONSE as _,
    ///< A touchlink (steal) attempt was made when a node is already connected
    /// to a centralized security network. A node was instructed to form a
    /// network when it did not have a logical type of either Zigbee coordinator
    /// or Zigbee router.
    NotPermitted = EZB_BDB_STATUS_NOT_PERMITTED as _,
    ///< The Trust Center link key exchange procedure has failed attempting to
    /// join a centralized security network.
    TclkExFailure = EZB_BDB_STATUS_TCLK_EX_FAILURE as _,
    ///< A commissioning procedure was forbidden since the node was not
    /// currently on a network.
    NotOnANetwork = EZB_BDB_STATUS_NOT_ON_A_NETWORK as _,
    ///< A commissioning procedure was forbidden since the node was currently
    /// on a network.
    OnANetwork = EZB_BDB_STATUS_ON_A_NETWORK as _,
    ///< The current operation (steering or formation) was cancelled by an app
    Cancelled = EZB_BDB_STATUS_CANCELLED as _,
    ///< A device announce sending has been failed (e.g. device announce
    /// haven't acked by parent router).
    DevAnnceSendFailure = EZB_BDB_STATUS_DEV_ANNCE_SEND_FAILURE as _,
}

/***r
pub(crate) impl From<ezb_bdb_comm_status_e> for BdbStatus {
    fn from(value: ezb_bdb_comm_status_e) -> Self {
        Self(value as _)
    }
}
***/
