[package]
name = "esp-zb-raw"
    # name used in 'examples' and the 'main' project
edition = "2024"
rust-version = "1.92"
publish = false

# NOTE: Did not manage to reliably use '[package.metadata.esp-idf-sys]' for steering these things,
#       _also_ for the higher '_' package. DO NOT BOTHER - use the '[env]' in '../.cargo/config.toml', instead.
#[package.metadata.esp-idf-sys]

[dependencies]
esp-idf-sys = { version = "0.37.2" }
log.workspace = true

[build-dependencies]
embuild.workspace = true

# ZCL clusters |1| are presented as features. This helps you clearly see, which clusters are implemented.
#
# (The same will likely apply to "HA Automation Device Types" |2| as well.)
#
#   |1|: https://docs.espressif.com/projects/esp-zigbee-sdk/en/latest/esp32c6/introduction.html#zcl-clusters
#   |2|: https://docs.espressif.com/projects/esp-zigbee-sdk/en/latest/esp32c6/introduction.html#ha-automation-device-types
#
[features]
default = [
    "zcl_basic",
    "zcl_identify",
]

# Supported Zigbee clusters; based on 'esp_zigbee_attribute.h':
zcl_basic = []
zcl_identify = []
zcl_groups = []
zcl_scenes = []
zcl_on_off = []
zcl_on_off_switch_config = []
zcl_level = []
zcl_color_control = []
zcl_time = []
zcl_binary_input = []
zcl_comissioning = []
zcl_shade_config = []
zcl_door_lock = []
zcl_ias_zone = []
zcl_ias_wd = []
zcl_temperature_meas = []
zcl_humidity_meas = []
zcl_ota = []
zcl_illuminance_meas = []
zcl_pressure_meas = []
zcl_flow_meas = []
zcl_electrical_meas = []
zcl_window_covering = []
zcl_occupancy_sensing = []
zcl_thermostat = []
zcl_fan_control = []
zcl_thermostat_ui_config = []
zcl_analog_input = []
zcl_analog_output = []
zcl_binary_output = []
zcl_analog_value = []
zcl_ec_measurement = []
zcl_ph_measurement = []
zcl_wind_speed_measurement = []
zcl_carbon_dioxide_measurement = []
zcl_pm2_5_measurement = []
zcl_multistate_input = []
zcl_multistate_output = []
zcl_multistate_value = []
zcl_diagnostics = []
zcl_meter_identification = []
zcl_drlc = []
zcl_dehumidification = []
zcl_binary_value = []
zcl_poll_control = []
zcl_device_temp_config = []
zcl_alarms = []

custom_cluster = []

# ESP32 devices with Zigbee support (currently targeting only C6).
# tbd. Can we drive 'esp-idf-sys' and the ESP-IDF toolchain with this, i.e. choose MCU from above?
esp32c6 = []

#---
# C '#ifdef's to consider porting as Rust features:
#
#   - CONFIG_ZB_ZED             { tbd. explain }
#   - CONFIG_ZB_GP_ENABLED      { tbd. explain }
#   - ZB_ENABLE_ZGB             Whether "green power" is enabled {...tbd. better explanation; is this a top-level ifdef?}
#   - ZB_DISTRIBUTED_SECURITY_ON { tbd. explain }
#
#   - CONFIG_ZB_ZCZR            "compile light (Router) source code"
#   - CONFIG_ESP_ZB_TRACE_ENABLE
#   - CONFIG_PM_ENABLE=y
#
#zb_zed = []     # 'CONFIG_ZB_ZED'   todo is?
# ...

# Though we envision always having 'defmt' enabled, it's good to provide an option.
#defmt = ["dep:defmt",
#    "esp-hal/defmt",
#    "esp-backtrace/defmt",
#    #?? "esp-bootloader-esp-idf?/defmt",
#    "esp-println?/defmt-espflash"
#]

#R? Features for the examples only! Rust gives no mechanism to have features that would apply only to 'examples/' (but
#R? not be exposed to downstream projects). In downstream projects, just IGNORE THESE: THE LIBRARY DOES NOT USE THEM!!
#R?
#? run_with_espflash = ["defmt", "dep:esp-println"]    # ?? "dep:esp-bootloader-esp-idf" ??
#? run_with_probe_rs = ["defmt", "dep:defmt-rtt"]

