[build]
target = "riscv32imac-esp-espidf"

# Instructions on what kind of library to build for the target.
#   - 'ldproxy' requires "std" even if our application would not.
#       - ..though our "apps/bin" do require "std", for Embassy + IDF to coexist ('embassy_time_driver'; long story...)
#   - panic type does not really matter: we catch it with a hook
#       .. to avoid a reset-loop if there is a repeating reason for a panic
#
# This works.
[unstable]
build-std = ["std", "panic_abort"]

[target.riscv32imac-esp-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor"
rustflags = [
    # "Required to obtain backtraces [on RISC-V only], however it may negatively impact the performance of your application."
    #
    # "Please note that when targeting a RISC-V device, you need to force frame pointers (i.e. "-C", "force-frame-pointers",
    # in your .cargo/config.toml); this is not required for Xtensa."
    #
    # Note: Interesting discussion in:
    #   - "`force-frame-pointers` flag isn't honored always unless std is recompiled as such"
    #       -> https://github.com/rust-lang/rust/issues/103711 (GitHub Issues; [closed])
    #
    # We... might not need this.
    #"-C", "force-frame-pointers",

    # "must be set for ESP-IDF 5.0 and above" |1|
    #
    # Time was 32bit in ESP-IDF 4.x and will be 64bit from now on.
    # |1|: https://github.com/esp-rs/esp-idf-sys/blob/master/BUILD-OPTIONS.md#rust-configuration-flags
    #
    "--cfg",  "espidf_time64"
]

# Note: Build environment does not get inherited in Cargo. To have the same settings for both 'raw' and '_', we
#       provide them here. You can make local overrides in either.
#
[env]
MCU = "esp32c6"
ESP_IDF_VERSION = "5.5.4"

ESP_IDF_TOOLS_INSTALL_DIR = "global"
    # "out":        '{cargo output}/espressif'
    # "global":     '~/.espressif'
    #               Also needs 'ldproxy' to be installed and configured (see above)
    # (default):    tooling to '{project-folder}/.embuild/espressif'

# Force 'esp_idf_component_manager' to be used.
# Note: This like does not matter, since "as per the build documentation it is "on"/"y" by default" |1|.
#   |1|: https://github.com/esp-rs/esp-idf-sys/issues/415#issuecomment-4234782429
#
#ESP_IDF_COMPONENT_MANAGER = "y"

#---
# ESP-IDF steering
#
# NOTE:
#   'relative' path definitions are relative to the project workspace root |*| (not the working directory).
#       |*|: https://github.com/esp-rs/esp-idf-sys/blob/master/BUILD-OPTIONS.md#esp_idf_sdkconfig_defaults-esp_idf_sdkconfig_defaults
#
# Allow 'esp-idf-sys' to find 'CMakeLists.txt', through which our copy of the Zigbee component.
# IMPORTANT so that the configurations in 'sdkconfig.defaults' regarding that component get applied.
ESP_IDF_PROJECT_DIR = { value = ".", relative = true }

# Optional: beg 'esp-idf-sys' to place the file in the local folder.
#   THIS DOES NOT WORK (Apr'26). Despite it, a build (within 'apps') creates the 'sdkconfig' within 'target',
#   not in this place.
#ESP_IDF_SDKCONFIG = { value = "sdkconfig", relative = true }

ESP_IDF_SDKCONFIG_DEFAULTS = { value = "sdkconfig.defaults", relative = true }

# MUST point to the subfolder that has '[[package.metadata.esp-idf-sys.extra_components]]' section,
# listing:
#   - esp_zigbee_lib
#
# The content is the _name_ of the package, _not_ a folder name!
#
# MANUAL TEST: To see all this is correct, see that 'extra_components: [ ... ]' in build output is not empty!!!
#
# Note: Undecided, whether this is better as 'raw' or 'apps'.
ESP_IDF_SYS_ROOT_CRATE = "esp-zb-raw"

#---
# Have this if you use Multipass VM, and a global 'target' folder.
CARGO_WORKSPACE_DIR = { value = "", relative = true }
    #
    # "[...] you have set 'CARGO_TARGET_DIR' and moved your target directory out of the crate root, then
    #   embuild is not able to locate the crate root. This will result in it among other things ignoring
    #   your local sdkconfig.defaults. In this case you must declare: [...]
    #     -> https://github.com/esp-rs/esp-idf-sys/blob/master/BUILD-OPTIONS.md#esp-idf-configuration

# Suppress some 'esp-idf-sys' warnings:
#   <<
#       [esp-idf-sys 0.37.2] clang diag: /home/ubuntu/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/esp-idf-sys-0.37.2/src/include/esp-idf/bindings.h:383:5: warning: macro expansion producing 'defined' has undefined behavior [-Wexpansion-to-defined]
#   <<
BINDGEN_EXTRA_CLANG_ARGS="-Wno-expansion-to-defined"

#---
# Trim down the set of components. This is OPTIONAL, but does reduce the build time.
#
# List of 'esp-idf-sys' default components:
#   <<
#       $ find ~/target -name project_description.json
#       $ cat {above} | jq common_component_reqs -C
#   <<
#   ..plus some that were figured out, experimentally.
#
ESP_IDF_COMPONENTS = "cxx;newlib;freertos;esp_hw_support;heap;log;soc;hal;esp_rom;esp_common;esp_system;riscv;main;driver;nvs_flash;wear_levelling;fatfs;spiffs;"
