#
# /.cargo/config.espidf.toml
#
# This is a repo specific workaround for 'cargo' not allowing to stop the '.cargo/config.toml'
# cascade.
#
# The problem we fix:
#   - insulating 'config' (which is not part of the larger workspace, and does not need esp-idf) from getting
#     these changes, *while* keeping its folder in the same level as other (which are part of the workspace)
#     sub-projects.
#
# How we fix it:
#   - This file has another name ('config.espidf.toml'); we symbolically link to it from all the workspace
#     folders, allowing us to distribute settings, without duplicating them.
#
[build]
target = "riscv32imac-esp-espidf"

# Instructions on what kind of library to build for the target.
#   - 'ldproxy' requires "std" even if our application would not.
#   - "apps/bin" do require it (even when 'no_std' + alloc), for Embassy + IDF to coexist ('embassy_time_driver'; long story...)
#   - panic type does not really matter: we catch it with a hook anyways to avoid a reset-loop
#
[unstable]
build-std = ["std", "panic_abort"]

[target.riscv32imac-esp-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor --partition-table partitions.csv"
    #
    # Note: You can try to get faster flash speed by:
    #   '--flash-freq 80mhz' (default is 40MHz); did not cause a speed-up with the author.
    #   '--flash-mode qio' (default is DIO); did not work for the author.
    #
    #   Such settings (if they work for you) can be placed in '.config/espflash/espflash.toml'

rustflags = [
    # "Required to obtain backtraces [on RISC-V only], however it may negatively impact the performance of your application."
    #
    # "Please note that when targeting a RISC-V device, you need to force frame pointers (i.e. "-C", "force-frame-pointers",
    # in your .cargo/config.toml); this is not required for Xtensa."
    #
    # Note: Interesting discussion in:
    #   - "`force-frame-pointers` flag isn't honored always unless std is recompiled as such"
    #       -> https://github.com/rust-lang/rust/issues/103711 (GitHub Issues; [closed])
    #
    # We... might not need this.
    #"-C", "force-frame-pointers",

    # "must be set for ESP-IDF 5.0 and above" |1|
    #
    # Time was 32bit in ESP-IDF 4.x and will be 64bit from now on.
    # |1|: https://github.com/esp-rs/esp-idf-sys/blob/master/BUILD-OPTIONS.md#rust-configuration-flags
    #
    "--cfg",  "espidf_time64"
]

# Note: Build environment does not get inherited in Cargo. To have the same settings for both 'raw' and '_', we
#       provide them here. You can make local overrides in either.
#
[env]
MCU = "esp32c6"
ESP_IDF_VERSION = "5.5.4"
#ESP_IDF_VERSION = "6.0.0"

ESP_IDF_TOOLS_INSTALL_DIR = "global"
    # "out":        '{cargo output}/espressif'
    # "global":     '~/.espressif'
    #               Also needs 'ldproxy' to be installed and configured (see above)
    # (default):    tooling to '{project-folder}/.embuild/espressif'

# Force 'esp_idf_component_manager' to be used.
# Note: This like does not matter, since "as per the build documentation it is "on"/"y" by default" |1|.
#   |1|: https://github.com/esp-rs/esp-idf-sys/issues/415#issuecomment-4234782429
#
#ESP_IDF_COMPONENT_MANAGER = "y"

#---
# ESP-IDF steering
#
# NOTE:
#   'relative' path definitions are relative to the project workspace root |*| (not the working directory).
#       |*|: https://github.com/esp-rs/esp-idf-sys/blob/master/BUILD-OPTIONS.md#esp_idf_sdkconfig_defaults-esp_idf_sdkconfig_defaults
#
# Allow 'esp-idf-sys' to find 'CMakeLists.txt', through which our copy of the Zigbee component.
# IMPORTANT so that the configurations in 'sdkconfig.defaults' regarding that component get applied.
ESP_IDF_PROJECT_DIR = { value = ".", relative = true }

# AVOIDS 'esp-idf-sys' from using an 'sdkconfig' that - by mistake - has been left in the project root.
ESP_IDF_SDKCONFIG = { value = "/tmp/.no-such" }

ESP_IDF_SDKCONFIG_DEFAULTS = { value = "apps/sdkconfig.defaults", relative = true }

# The name of the sub-project that has '[[package.metadata.esp-idf-sys.extra_components]]' section, listing:
#   - esp_zigbee_lib
#
# The content is the name of the package, _not_ a folder name!
#
# NOTE! If this is out of sync, the 'raw' build will break but not in any decent, helpful manner!  You will see this
#       warning somewhere in the output:
#           <<
#               [esp-idf-sys 0.37.2] cargo:warning=the crate given by `ESP_IDF_SYS_ROOT_CRATE` does not exist in this workspace
#           <<
#
#       The best way is to check the output JSON starting "Build configuration: BuildConfig {", every now and then.
#       If things work, you did get this right! ⛱️☀️
#
# Note: Undecided, whether this is better at 'raw' or 'apps'.
#
# Note 3: The _real_ error you'll get if this is wrong is:
#       <<
#           $ make manual
#           Makefile:68: *** No 'managed_components' pulled by Rust build.  Stop.
#       <<
ESP_IDF_SYS_ROOT_CRATE = "ezb-node-raw"

#---
# Have this if you use Multipass VM, and a global 'target' folder.
CARGO_WORKSPACE_DIR = { value = "", relative = true }
    #
    # "[...] you have set 'CARGO_TARGET_DIR' and moved your target directory out of the crate root, then
    #   embuild is not able to locate the crate root. This will result in it among other things ignoring
    #   your local sdkconfig.defaults. In this case you must declare: [...]
    #     -> https://github.com/esp-rs/esp-idf-sys/blob/master/BUILD-OPTIONS.md#esp-idf-configuration

# Suppress some 'esp-idf-sys' warnings:
#   <<
#       [esp-idf-sys 0.37.2] clang diag: /home/ubuntu/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/esp-idf-sys-0.37.2/src/include/esp-idf/bindings.h:383:5: warning: macro expansion producing 'defined' has undefined behavior [-Wexpansion-to-defined]
#   <<
BINDGEN_EXTRA_CLANG_ARGS="-Wno-expansion-to-defined"

#---
# Trim down the set of components (~1050 -> ~930). OPTIONAL, but reduces the build time.
#
# List of 'esp-idf-sys' default components:
#   <<
#       $ find ~/target -name project_description.json
#       $ cat {above} | jq common_component_reqs -C
#   <<
#   ..plus some that were figured out, experimentally.
#
#   Note: 'esp-idf-svc-0.52.1' seems to need 'fatfs' (on apps level).
#
ESP_IDF_COMPONENTS = """\
  cxx;newlib;freertos;esp_hw_support;heap;log;soc;hal;esp_rom;esp_common;esp_system;riscv;main;driver;\
  nvs_flash;wear_levelling;spiffs;fatfs;\
"""
