[build]
target = "riscv32imac-esp-espidf"

# Instructions on what kind of library to build for the target.
#   - 'ldproxy' requires "std" even if our application would not.
#       - ..though our "apps/bin" do require "std", for Embassy + IDF to coexist ('embassy_time_driver'; long story...)
#   - panic type does not really matter: we catch it with a hook
#       .. to avoid a reset-loop if there is a repeating reason for a panic
#
# This works.
[unstable]
build-std = ["std", "panic_abort"]

[target.riscv32imac-esp-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor"
rustflags = [
    # "Required to obtain backtraces [on RISC-V only], however it may negatively impact the performance of your application."
    #
    # "Please note that when targeting a RISC-V device, you need to force frame pointers (i.e. "-C", "force-frame-pointers",
    # in your .cargo/config.toml); this is not required for Xtensa."
    #
    # Note: Interesting discussion in:
    #   - "`force-frame-pointers` flag isn't honored always unless std is recompiled as such"
    #       -> https://github.com/rust-lang/rust/issues/103711 (GitHub Issues; [closed])
    #
    # We... might not need this.
    #"-C", "force-frame-pointers",

    # "must be set for ESP-IDF 5.0 and above" |1|
    #
    # Time was 32bit in ESP-IDF 4.x and will be 64bit from now on.
    # |1|: https://github.com/esp-rs/esp-idf-sys/blob/master/BUILD-OPTIONS.md#rust-configuration-flags
    #
    "--cfg",  "espidf_time64"
]

# Note: Build environment does not get inherited in Cargo. To have the same settings for both 'raw' and '_', we
#       provide them here. You can make local overrides in either.
#
[env]
MCU = "esp32c6"
ESP_IDF_VERSION = "5.5.4"

ESP_IDF_TOOLS_INSTALL_DIR = "global"
    # "out":        '{cargo output}/espressif'
    # "global":     '~/.espressif'
    #               Also needs 'ldproxy' to be installed and configured (see above)
    # (default):    tooling to '{project-folder}/.embuild/espressif'

ESP_IDF_SDKCONFIG_DEFAULTS = "sdkconfig.defaults"

# Important, but when ???
#ESP_IDF_SYS_ROOT_CRATE = "esp-idf-raw"

# Have this if you use Multipass VM, and a global 'target' folder.
CARGO_WORKSPACE_DIR = { value = "", relative = true }
    #
    # "[...] you have set 'CARGO_TARGET_DIR' and moved your target directory out of the crate root, then
    #   embuild is not able to locate the crate root. This will result in it among other things ignoring
    #   your local sdkconfig.defaults. In this case you must declare: [...]
    #     -> https://github.com/esp-rs/esp-idf-sys/blob/master/BUILD-OPTIONS.md#esp-idf-configuration

# Suppress some 'esp-idf-sys' warnings:
#   <<
#       [esp-idf-sys 0.37.2] clang diag: /home/ubuntu/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/esp-idf-sys-0.37.2/src/include/esp-idf/bindings.h:383:5: warning: macro expansion producing 'defined' has undefined behavior [-Wexpansion-to-defined]
#   <<
BINDGEN_EXTRA_CLANG_ARGS="-Wno-expansion-to-defined"
