[package]
name = "ezb-node-config"
version = "0.0.1"
edition = "2024"
rust-version = "1.94"

[dependencies]
#humantime-serde = { version = "1.1.1", optional = true }
quote = { version = "1.0", optional = true }
prettyplease = { version = "0.2", optional = true }
serde = { version = "1.0", features = ["derive", "alloc"], default-features = false, optional = true }
syn = { version = "2.0", features = ["full"], optional = true }
toml = { version = "1.1.2", features = ["serde"], optional = true }

[features]
default = []
toml = ["quote", "prettyplease", "serde", "syn", "dep:toml"]

coordinator = []
router = []
end_device_UNTESTED = []

ep_color_dimmable_light = []

#[[test]]
#name=
#features=toml,coordinator,router,ep_color_dimmable_light
