[package]
name = "esp-zb"
version = "0.0.1"
edition = "2024"
rust-version = "1.94"

[dependencies]
esp-zb-raw = { path = "../raw" }

log.workspace = true

esp-idf-sys = { workspace = true, default-features = false }
    # just core

[dev-dependencies]
esp-idf-sys = { workspace = true, features = ["alloc_handler", "binstart"], default-features = false }
    # just core; we do our own panic handler

esp-idf-hal = { version = "0.46.2", features = ["alloc"], default-features = false }
    # hardware access

#esp-backtrace = { version = "0.18.1", features = ["panic-handler"] } # "esp32c6"

[build-dependencies]
embuild.workspace = true

#[dev-dependencies]
#embassy-executor = { version = "0.7.0", features = ["task-arena-size-12288"] }
#embassy-futures = { version = "0.1.2" }
#embassy-sync    = { version = "0.7.2" }
#embassy-time    = { version = "0.5.0", features = ["defmt", "defmt-timestamp-uptime"] }

#esp-backtrace   = { version = "0.17.0", features = ["panic-handler", "defmt", "esp32c6", "semihosting"] }

[features]
default = ["esp32c6"]

#defmt = ["dep:defmt", "dep:defmt-rtt"]

esp32c6 = [
    "esp-zb-raw/esp32c6",
    #"esp-backtrace/esp32c6",
]

[lints]
workspace = true

[[example]]
name = "a"
required-features = ["esp32c6"]

[[example]]
name = "light"
required-features = ["esp32c6"]
