[package]
name = "esp-zb"
version = "0.0.1"
edition = "2024"
rust-version = "1.94"

[dependencies]
esp-zb-raw = { path = "../raw" }

log.workspace = true

esp-idf-sys = { workspace = true, default-features = false }
    # just core

[dev-dependencies]
esp-idf-sys = { workspace = true, features = ["alloc_handler", "binstart"], default-features = false }
    # just core; we do our own panic handler

[build-dependencies]
embuild.workspace = true

[features]
default = ["esp32c6"]

esp32c6 = [
    "esp-zb-raw/esp32c6",
]

[lints]
workspace = true

[[example]]
name = "a"
required-features = ["esp32c6"]
