[package]
name = "esp_zb_expose_builtin_led"
edition = "2024"
rust-version = "1.89"
publish = false

[dependencies]
esp-idf-svc = { version = "0.52" }
log = "0.4"

# --- Optional Embassy Integration ---
# esp-idf-svc = { version = "0.51", features = ["critical-section", "embassy-time-driver", "embassy-sync"] }

# If you enable embassy-time-driver, you MUST also add one of:

# a) Standalone Embassy libs ( embassy-time, embassy-sync etc.) with a foreign async runtime:
# embassy-time = { version = "0.4.0", features = ["generic-queue-8"] } # NOTE: any generic-queue variant will work

# b) With embassy-executor:
# embassy-executor = { version = "0.7", features = ["executor-thread", "arch-std"] }

# NOTE: if you use embassy-time with embassy-executor you don't need the generic-queue-8 feature

# --- Temporary workaround for embassy-executor < 0.8 ---
# esp-idf-svc = { version = "0.51", features = ["embassy-time-driver", "embassy-sync"] }
# critical-section = { version = "1.1", features = ["std"], default-features = false }

#defmt           = { version = "1.0", optional = true }
esp-zb      = { path = "../main", features = [] } # "defmt"

[build-dependencies]
embuild = "0.33"

#[dev-dependencies]
#defmt-rtt       = { version = "1.0" }
#semihosting     = {  version = "0.1.20" }

[features]
default = ["esp32c6"]

#defmt = ["dep:defmt", "esp-zb-raw/defmt", "esp-hal/defmt"]

esp32c6 = [] #R ["esp-hal/esp32c6"]

# As created by 'esp-idf-template'
[profile.release]
opt-level = "s"
