[package]
name = "ezb-node-config"
version = "0.0.2"
edition = "2024"
rust-version = "1.94"

[dependencies]
#humantime-serde = { version = "1.1.1", optional = true }
quote = { version = "1.0", optional = true }
prettyplease = { version = "0.3", optional = true }
proc-macro2 = { version = "1.0", optional = true }
serde = { version = "1.0", features = ["derive", "alloc"], default-features = false, optional = true }
syn = { version = "3.0", features = ["full"], optional = true }
toml = { version = "1.1.2", features = ["serde"], optional = true }

[features]
default = ["toml"]

# Applications must enable 'toml', either directly or via the default.
# API layer works without it.
toml = ["quote", "prettyplease", "proc-macro2", "serde", "syn", "dep:toml"]

coordinator = []
router = []
#end_device_UNTESTED = []

# --- Device types

_dt_all = ["dt_color_dimmable_light", "dt_color_dimmer_switch", "dt_ias_cie"]

# implements SERVER side of (clusters):
#   HA::on_off
#   HA::level_control
#   HA::color_control
dt_color_dimmable_light = []

# implements CLIENT side of (clusters):
#   HA::on_off
#   HA::level_control
#   HA::color_control
dt_color_dimmer_switch = []

# implements SERVER side of (clusters):
#   HA::ias_zone    // receives Door/Window/Movement alert information
dt_ias_cie = []

# --- Additional ZCL profiles (all HA)
#
# CURRENTLY INACTIVE. Let's just bring in the code we need; see #later if we want to feature-gate them.
#
#cl_power_config = []  # HA::power_config (server); collects battery information
