#
# Development helper targets. Optional.
#
# Usage:
#   <<
#     $ just {--list|{..target..}}
#   <<
#
default:
	@just --list

all_profiles := \
	"color_dimmable_light,"+\
	"color_dimmer_switch,"+\
	""

b: build
build:
	cargo build --release --features toml,{{all_profiles}}

t: test
test:
	cargo test --features toml
