#
# Development helper targets. Optional.
#
# Usage:
#   <<
#     $ just {--list|{..target..}}
#   <<
#
alias b := build

default:
	@just --list

all_dts := \
	"dt_color_dimmable_light,"+\
	"dt_color_dimmer_switch,"+\
	""

build:
	cargo build --release --features toml,{{all_dts}}

#test:
#	cargo test --features toml
