[package]
name = "ezb-node-apps"
version = "0.0.1"
edition = "2024"
rust-version = "1.94"
publish = false

# Inform 'espflash'
#
# We are anyways pointing the flashing command ('espflash') directly at the partition table, so keeping this hidden,
# to avoid confusion. 3-May-26
#
[package.metadata.espflash]
partition_table = "partitions.csv"

[dependencies]
ezb-node = { path = "../api", features = [] }   # "coordinator", "router"

anyhow = { version = "1.0"}

log.workspace = true

esp-idf-hal = { workspace = true }

# 'esp-idf-svc' is *vital for Embassy integration*
#   - 'embassy_time_driver' comes through there, which is essential in tying ESP-IDF and Embassy together.
#   - 'alloc' is needed for logging
#   + 'native' needed for linking (likely; tbd. confirm)
#
esp-idf-svc = { workspace = true, features = ["embassy-time-driver", "alloc", "binstart", "native", "critical-section"], default-features = false }

embassy-executor = { version = "0.10", features = ["executor-thread", "platform-std"] }
embassy-sync     = { version = "0.8.0" }
embassy-time    = { workspace = true, features = ["generic-queue-8"] }
    # generic-queue-X: presumably, "any 'generic-queue' implementation will work"

futures-util = { version = "0.3.32" }

[build-dependencies]
ezb-node-config = { path = "../config", features = ["toml", "color_dimmable_light", "color_dimmer_switch"] }
anyhow = { version = "1.0" }
embuild.workspace = true

[features]
default = ["esp32c6", "_coordinator", "_router"]

esp32c6 = [
    "ezb-node/esp32c6",
]

# Note: By defining the creation features like this, we get them in one place.
_coordinator = ["ezb-node-config/coordinator", "ezb-node/coordinator"]
_router = ["ezb-node-config/router", "ezb-node/router"]

[lints]
workspace = true

[[bin]]
name = "1-light"
path = "demo/1/light/main.rs"
required-features = ["esp32c6", "ezb-node/ep_color_dimmable_light"]

[[bin]]
name = "1-switch"
path = "demo/1/switch/main.rs"
required-features = ["esp32c6", "ezb-node/ep_color_dimmer_switch", "ezb-node/match_color_dimmable_light"]

[[bin]]
name = "2-door"
path = "demo/2/main.rs"
required-features = ["esp32c6", "ezb-node/ep_abc", "ezb-node/match_def"]
