[package]
name = "esp-zb-examples"
version = "0.0.1"
edition = "2024"
rust-version = "1.94"
publish = false

# Inform 'espflash'
[package.metadata.espflash]
partition_table = "partitions.csv"

[dependencies]
esp-zb = { path = "../api" }

log.workspace = true

# 'esp-idf-svc' *is* needed for Embassy integration
#   - 'embassy_time_driver' comes through there, which is a vital part in tying ESP-IDF and Embassy together.
#   - 'alloc' is needed for logging
#
esp-idf-svc = { version = "0.52.1", features = ["embassy-time-driver", "alloc", "binstart"], default-features = false }
    # defaults to: "binstart", "std"
    #
    # Note: Do not hesitate from bringing 'std' in, if there are problems. The above is merely the *slimmest*
    #       setup the author thinks will work. There may be unnoticed side effects in not bringing full 'std'.

embassy-executor = { version = "0.10", features = ["executor-thread", "platform-std"] }
embassy-time    = { workspace = true, features = ["generic-queue-8"] }
    # generic-queue-X: 'esp-idf-template' comments: "any 'generic-queue' implementation will work"

# Note: No need for 'embassy-sync' or 'critical-section' because we use Embassy only on a single (FreeRTOS) thread.

time = { version = "0.3.47" }

[build-dependencies]
embuild.workspace = true

[features]
default = ["esp32c6"]

esp32c6 = [
    "esp-zb/esp32c6",
]

[lints]
workspace = true

[[bin]]
name = "a"
path = "bin/a.rs"
required-features = ["esp32c6"]

[[bin]]
name = "light"
path = "bin/light.rs"
required-features = ["esp32c6"]
