#!/usr/bin/env just --justfile

#
# Development helper targets. Optional.
#
# Requires:
#	- jq
#
default:
    @just --list

alias lb := light-build
alias lr := light-run
alias sb := switch-build
alias sr := switch-run

# For 'esp-idf-sys' builds, 'nightly' is a must. 'rust-toolchain.toml' adds it to us, and may enforce a specific version.
# This is only for commentary purposes.
nightly := ""

target_dir := `cargo metadata --format-version 1 --no-deps | jq -r '.target_directory'`

# 1-light
[group('light')]
light-build:
	cargo {{nightly}} build --release -vv --bin 1-light --features esp32c6,ezb-node/ep_color_dimmable_light \
		--jobs 1

[group('light')]
lbx:
	cargo {{nightly}} build --release -vv --bin 1-light --features esp32c6,ezb-node/ep_color_dimmable_light

[group('light')]
light-run:
	cargo {{nightly}} run --release -vv --bin 1-light --features esp32c6,ezb-node/ep_color_dimmable_light

# 1-switch
[group('switch')]
switch-build:
	cargo {{nightly}} build --release -vv --bin 1-switch --features esp32c6,ezb-node/ep_color_dimmer_switch,ezb-node/match_color_dimmable_light \
		--jobs 1

[group('switch')]
switch-run:
	cargo {{nightly}} run --release -vv --bin 1-switch --features esp32c6,ezb-node/ep_color_dimmer_switch,ezb-node/match_color_dimmable_light

# List the *last* 'sdkconfig'
echo-sdkconfig-path:
	@\
	out=$(find {{target_dir}} -name sdkconfig -printf "%T@ %p\n" | sort -n | tail -n 1 | cut -d' ' -f2-); \
	if [ -z "$out" ]; then \
		printf >&2 "Error: No 'sdkconfig' found in {{target_dir}}\n"; \
		false; \
	fi; \
	echo "$out"
