#!/usr/bin/env just --justfile

#
# Development helper targets. Optional.
#
# Usage:
#   <<
#     $ just {--list|{..target..}}
#   <<
#
default:
    @just --list

light_features := "esp-zb/ep_color_dimmable_light"

[group('light')]
lb: light-build
light-build:
    cargo build --release -vv --bin light --features {{light_features}}

[group('light')]
lr: light-run
light-run:
    cargo run --release -vv --bin light --features {{light_features}}
