#
# Coordinator to listen to a Door/Window sensor.
#
# Provides:
#   - "ias_cie" HA profile
#       - "ias_zone" (client role)
#   - "power_config" (server role)  <-- tbd. which one is it, really?
#
[network]
primary_channels = [11, 15, 20, 25]     # 11, 15, 20 or 25 are best for commercial devices (google.ai)
secondary_channels = "all"

[platform]
storage_partition_name = "nvs"  # since esp-zigbee-lib 2.0.4 (could also be omitted from the config?)

[node]
type = "coordinator"
install_code_policy = false
    # false: allow "well known key" joining
max_children = 5

[endpoint.defaults]
manufacturer_name = "Espressif"
model_identifier = "ESP32-C6 gateway"

[endpoint.1]
device_type = "HA::ias_cie"
    # HA = "Home Automation"
    # IAS = "Intrusion Alarm System"
    # CIE = "Control and Indicating Equipment"

additional_server_clusters = [
    "HA::power_config"      # remaining battery
]
