[package]
name = "ezb-node"
version = "0.0.1"
edition = "2024"
rust-version = "1.94"

[dependencies]
ezb-node-raw = { workspace = true }
ezb-node-config = { workspace = true, default-features = false }

log.workspace = true

embassy-sync = { version = "0.8.0", features = ["std"] }    # "std": thread mode
embassy-time = { workspace = true }

# 'esp-idf-svc' is vital for:
#   - 'std' for RTOS threading (running Zigbee task separate from the application task)
#   + 'native' (from workspace) needed for linking
#
esp-idf-svc = { workspace = true, default-features = false, features = ["std", "native"] }

bitflags = { version = "2.11.1" }

async-stream = { version = "0.3.6" }
futures-util = { version = "0.3.32" }

strum = { version = "0.28", features = ["derive"] }

[build-dependencies]
embuild.workspace = true

[features]
default = ["esp32c6"]
coordinator = ["ezb-node-config/coordinator"]
router = ["ezb-node-config/router"]
#end_device_UNTESTED = [] #["ezb-node-config/end_device"]

# Device types
_dt_all = ["dt_color_dimmable_light", "dt_color_dimmer_switch", "dt_ias_cie"]

dt_color_dimmable_light = ["ezb-node-config/dt_color_dimmable_light"]
dt_color_dimmer_switch = ["ezb-node-config/dt_color_dimmer_switch"]
dt_ias_cie = ["ezb-node-config/dt_ias_cie"]

# Device types on the other side (find, bind, access).
#
# Note: We do differentiate between what-you-want-to-bind-with here, but not in the code. Experimenting.
#
_remote_any = []
remote_dt_color_dimmable_light = ["_remote_any"]
remote_cl_power_config = ["_remote_any"]

esp32c6 = [
    "ezb-node-raw/esp32c6",
]

# Extra safety (debugging) feature:
#   - Leaks some memory (binding structs), in order to warrant assumptions on C callback behaviour.
_extra_safety = []

[lints]
workspace = true
