[package]
name = "ezb-node"
version = "0.0.1"
edition = "2024"
rust-version = "1.94"

[dependencies]
ezb-node-raw = { path = "../raw" }
ezb-node-config = { path = "../config" }

log.workspace = true

embassy-executor = { version = "0.10.0" }
embassy-time = { workspace = true, features = ["log"] }

esp-idf-sys = { workspace = true, default-features = false }
    # just core

bitflags = { version = "2.11.1" }

strum = { version = "0.28", features = ["derive"] }

[build-dependencies]
embuild.workspace = true

[features]
default = ["esp32c6"]
coordinator = ["ezb-node-config/coordinator"]
router = ["ezb-node-config/router"]
end_device_UNTESTED = [] #["ezb-node-config/end_device"]
    # NOT TESTED; to allow speculative coding. Enable to create a node in EndDevice (only) role.

touchlink = []

# Device types
ep_color_dimmable_light = []

esp32c6 = [
    "ezb-node-raw/esp32c6",
]

[lints]
workspace = true
