[package]
name = "esp-zb"
version = "0.0.1"
edition = "2024"
rust-version = "1.94"

[dependencies]
esp-zb-raw = { path = "../raw" }

log.workspace = true

embassy-executor = { version = "0.10.0" }
#embassy-futures = { version = "0.1.2" }
embassy-time = { workspace = true, features = ["log"] }

esp-idf-sys = { workspace = true, default-features = false }
    # just core

bitflags = { version = "2.11.1" }
once_cell = { version = "1.21", default-features = false }

#r [dev-dependencies]
#r esp-idf-sys = { workspace = true, features = ["alloc_handler", "binstart"], default-features = false }
#r    # just core

[build-dependencies]
embuild.workspace = true

[features]
default = ["esp32c6"]
coordinator = []    # enable building as a Coordinator (in addition to Router and EndDevice)
router = []     # enable building as a Router (in addition to EndDevice)
    # Note: while a Coordinator can always also be a Router, we don't do feature-level derivation.
    #       This is partly for code clarity, but also we opt out the *creation level code* that is not
    #       specifically opted-in for. WIP...

touchlink = []

# Device types
ep_color_dimmable_light = []

esp32c6 = [
    "esp-zb-raw/esp32c6",
]

[lints]
workspace = true
