#!/usr/bin/env just --justfile

#
# Development helper targets. Optional.
#
# Usage:
#   <<
#     $ just {--list|{..target..}}
#   <<
#
default:
    @just --list

# For 'esp-idf-sys' builds, 'nightly' is a must. 'rust-toolchain.toml' adds it to us, and may enforce a specific version.
# This is only for commentary purposes.
nightly := ""

b: build
build:
	cargo {{nightly}} build --release -vv \
		--jobs 1 \
		--features coordinator,router,_ep_all
