#!/usr/bin/env just --justfile

default:
    @just --list

# For 'esp-idf-sys' builds, 'nightly' is a must. 'rust-toolchain.toml' adds it to us, and may enforce a specific version.
# This is only for commentary purposes.
nightly := ""

alias b:= build

build:
	cargo {{nightly}} build --release -vv \
		--jobs 1 \
		--features coordinator,router,_ep_all

# It is possible to also make a coordinator without any endpoint profiles.
build-bare:
	cargo {{nightly}} build --release -vv \
		--jobs 1 \
		--features coordinator
